02-components block
js-tasks-ru/vue-20201022_tamagotchi pull request #5
Opened 2020-11-15 20:43 UTC by Tamagotchi9

MeetupPage was splited up into components

2020-11-15 20:50 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
MeetupPageComponent
+ MeetupPage должен быть определён
+ MeetupView должен иметь обязательный параметр meetup с объектом митапа
+ MeetupView должен показывать изображение, описание, информацию и программу митапа соответствующими компонентами
+ MeetupCover должен иметь необязательные строковые параметры link и title
+ MeetupCover должен выводить изображение митапа
+ MeetupCover не должен удалять изображение по умолчанию в случае отсутствия ссылки на изображение
+ MeetupCover должен выводить название митапа
+ MeetupDescription должен иметь необязательный строковый параметр description
+ MeetupDescription должен выводить описание митапа
+ MeetupInfo должен иметь обязательные строковые параметры organizer, place и обязательный параметр с датой date
+ MeetupInfo должен выводить краткое описание митапа
+ MeetupAgenda должен иметь параметр массив agenda
+ MeetupAgenda должен выводить программу через компоненты MeetupAgendaItem
+ MeetupAgendaItem должен иметь обязательный параметр объект agendaItem
+ MeetupAgendaItem должен выводить время
+ MeetupAgendaItem должен выводить заголовок по умолчанию
+ MeetupAgendaItem должен выводить правильную иконку для регистрации
+ MeetupAgendaItem должен выводить доклад
```
```diff
Компонент CounterButton
+ CounterButton должен иметь числовой входной параметр count со значением 0 по умолчанию
+ CounterButton должен рендерить кнопку с текстом count
+ CounterButton должен иметь count 0 по умол��анию
+ CounterButton должен порождать событие increment с увеличенным на 1 значением по клику
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-11-15 22:09 UTC, ShGKme requested changes
Требуется установить начальное значение митапа в `null` вместо `{}`

2020-11-15 22:09 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +    addCounter(count) {
Параметр count не нужен, так как он есть в параметрах.

2020-11-15 22:09 UTC, ShGKme commented on 02-components/02-MeetupPageComponent/MeetupPage.js
> +      meetup: {},
Пустой объект - не частный случай объекта с описанием митапа. Хотя установка начального значения в {} избавляет от простых ошибок, она не избавляет от ошибок полностью, оставляя более трудно-находимые ошибки. Лучше начальным значением указать null и делать проверки. Например, сейчас на время загрузки митапа отображается "сломанная" страница с пустыми значениями.

На `meetup-view` далее можно просто поставить `v-if`, чтобы выводить компонент с описанием митапа только тогда, когда данные митапа для вывода уже есть.

*Эту проблему потребуется исправить, чтобы задача была зачтена.*

2020-11-16 11:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-11-16 12:25 UTC, ShGKme approved these changes
Принято 👍

2020-11-16 12:25 UTC, merged