Solution of 06-deep-vue 01-Buttons
js-tasks-ru/vue-20201022_tamagotchi pull request #9
Opened 2021-03-05 15:53 UTC by Tamagotchi9

2021-03-05 15:53 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-03-09 16:40 UTC, ShGKme requested changes
Требуются исправления в обеих задачах...

2021-03-09 16:40 UTC, ShGKme commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +  </button>
Компонент должен быть обёрткой над элементом `tag`, а не всегда кнопкой. Например, иногда требуется, чотбы элемент был ссылкой, но выглядел, как кнопка. Здесь поможет [Динамический компонент](https://ru.vuejs.org/v2/guide/components.html#%D0%94%D0%B8%D0%BD%D0%B0%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5-%D0%BF%D0%B5%D1%80%D0%B5%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2)

Параметры и атрибуты на него могут передаваться самые разные, а не только `href`, `target`. Требуется передавать все атрибуты.

2021-03-09 16:40 UTC, ShGKme commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +  },
Этому компоненту не требуется локальное состояние. В нём нет данных, которые как-то меняются. Он зависит только от входных параметров.

2021-03-09 16:40 UTC, ShGKme commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +    <slot name="default"></slot>
Имя `default` можно не указывать

2021-03-09 16:40 UTC, ShGKme commented on 06-deep-vue/02-AppInput/components/AppInput.vue
> +    </slot>
Значение слота по умолчанию здесь не требуется. Если иконка не передана, то её нет, и она не нужна. Не требуется показывать какую-то иконку всегда.

2021-03-09 16:40 UTC, ShGKme commented on 06-deep-vue/02-AppInput/components/AppInput.vue
> +    ></textarea>
От дублирования кода можно избавиться с динамическим компонентом

2021-03-09 16:40 UTC, ShGKme commented on 06-deep-vue/02-AppInput/components/AppInput.vue
> +    },
Это свойство всегда истинно, так как в `this.$slots` хранится объект с содержимым всех слотов. Если их нет, то просто будет пустой объект, но это истинное значение.

2021-03-09 16:40 UTC, ShGKme commented on 06-deep-vue/02-AppInput/components/AppInput.vue
> +  },
Требуется также помнить о том, что `this.$slots` - не реактивное свойство.

2021-03-15 13:28 UTC, ShGKme approved these changes
Все задачи приняты 👍

2021-03-15 13:29 UTC, merged